service: email-scheduler

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  profile: default
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - Ref: EmailSchedulingStateMachine
    - Effect: "Allow"
      Action:
        - "ses:SendTemplatedEmail"
      Resource: arn:aws:ses:#{AWS::Region}:#{AWS::AccountId}:identity/${self:custom.EMAIL_SENDER_ADDRESS}

custom:
  EMAIL_SENDER_ADDRESS: "ecommercechanozu@gmail.com"

package:
  individually: true

functions:
  ScheduleEmail:
    handler: src/lambdas/schedule-email.handle
    environment:
      STATEMACHINE_ARN: ${self:resources.Outputs.EmailSchedulingStateMachine.Value}
  SendEmail:
    handler: src/lambdas/send-email.handle
    environment:
      EMAIL_SENDER_ADDRESS: ${self:custom.EMAIL_SENDER_ADDRESS}

stepFunctions:
  stateMachines:
    EmailSchedulingStateMachine:
      name: EmailSchedulingStateMachine
      definition:
        Comment: "Schedules an email to be sent at a future date"
        StartAt: WaitForDueDate
        States:
          WaitForDueDate:
            Type: Wait
            TimestampPath: "$.dueDate"
            Next: SendEmail
          SendEmail:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage, 'dev'}-SendEmail"
            End: true

resources:
  Outputs:
    EmailSchedulingStateMachine:
      Description: The ARN of the EmailSchedulingStateMachine
      Value:
        Ref: EmailSchedulingStateMachine

plugins:
  - serverless-step-functions
  - serverless-webpack
  - serverless-pseudo-parameters
